### PR TITLE
CoronaTrackerTweetScraper2.py

### PR DESCRIPTION
**Pull request by realvivekganta**
Updated Tweet Scraper for the CoronaTracker Project

### CODE REVIEW

**Comment by realvivekganta** [comment]
Hey, @samueljklee,

 I have updated the Tweet Scraper. Please let me know when you accept the pull request and when it's been successfully uploaded to the project. If there happens to be anything else just let me know and ill take a look at it. 

Thanks again, Vivek

**Comment by samueljklee** [comment]
Hey Vivek, thanks for working on this. However the code itself is not in python-format (file name is `CoronaTrackerTweetScraper2`), could you update that?

**Comment by realvivekganta** [comment]
@samueljklee Yup will do. Thanks again, Sam. Let me know if there's anything else,

- Vivek G

**Comment by samueljklee** [comment]
@realvivekganta  My bad, I might have not been clear previously, the file you've added to this PR is just a text file, that's the file you need to update since I will have to run it to check the output.

**Comment by samueljklee** [comment]
@realvivekganta 's changes have been merged [here](https://github.com/theleadio/coronatracker/commit/0f851beb2afecb081c4f175142836da7224fe86d) closing this PR.

**Pull request closed without merging**
