### PR TITLE
CoronaVirusTweetScraper2

### PR DESCRIPTION
**Pull request by realvivekganta**
A tweet bot that scrapes twitter to find data and information regarding the wufan coronavirus.

### CODE REVIEW

**Comment by samueljklee** [comment]
Is the output of the script pushed into coronatracker database? If so I can help with reviewing the code. If not, do you want to push it to the database?

**Comment by realvivekganta** [comment]
Yup, the output of the code should be pushed into the CoronaTracker database.

**Comment by realvivekganta** [comment]
Let me know when you have reviewed the code. If there are any issues, I can fix them before we deploy the twitter bot into the main repository.

**Comment by realvivekganta** [comment]
@samueljklee

**Comment by samueljklee** [comment]
@realvivekganta  Sorry for the late reply. Is it currently in the database? or will this be following the crawled article format? I'm a little confused because tweets do not have the regular article attributes (url, content, title, author, image, ...). Unless this is used for other purposes. Can you confirm?

**Comment by realvivekganta** [comment]
@samueljklee it should currently be in the database if it is not then yes I would like to push it to the database. Hmm, that is odd that the tweets don't have the regular article attributes, do you think you could review it to see if there are any errors in the code?

**Comment by samueljklee** [comment]
@realvivekganta The code itself seems pretty simple thanks to the library. Could you update it such that it'll have the production behavior? Which is: if the tag line isn't being used, feel free to remove that, since this will be pushed to the database, please do include the code to push to the database so it'll be reproducible for others. an example on how to do so could be found in `db_connector.py`. Since this scraper will be a tweet scraper instead of an article scraper, you might want to ask the team on what is required or will be needed so it'll be useful for the research team to use.

**Pull request closed without merging**
