### PR TITLE
Twitter Bot 2 patch 1

### PR DESCRIPTION
**Pull request by realvivekganta**
@samueljklee Ah Gotcha, sorry about that. The file should now be in python-format. Please let me know once it has been merged.

### CODE REVIEW

**Comment by samueljklee** [comment]
Hello @realvivekganta,  few notes:
- could you add comments on how to run this? And what is the output?
- are you storing this into the database? (inserting to database can be seen [here](https://github.com/theleadio/coronatracker/tree/develop/scraping/DatabaseConnector))
- `twitter_scraper` is a library that users have to install, can you add it into the `requirements.txt` so everyone can install

Let me know if you need help!

**Comment by realvivekganta** [comment]
Hey @samueljklee 

Sure I can add comments. The output can be seen in the JSON file. Yes, I'm storing this in the database. can you assist me with inserting it into the database?

-Vivek G

**Comment by samueljklee** [comment]
Sure, are you in the Coronatracker slack channel? Ping me there @realvivekganta

**Comment by realvivekganta** [comment]
@samueljklee sounds good

**Pull request merged**
